--offline avoids github tests (no internet); clone depth 1
sindresorhus/awesome-lint pull request #183
Opened 2023-12-30 23:33 UTC by WillForan

I was traveling and noticed awesome-lint was very slow without access to github.com. 

I'm sure that's an unusual use case, so maybe it's not worth a dedicated CLI. But in case otherwise, here's the change that I think would avoid needing internet access.

2023-12-31 05:58 UTC, sindresorhus commented
Would be better to add a timeout for the slow operation.

2023-12-31 16:22 UTC, WillForan commented
`timeout` seems like a good general solution. 2 implementation questions:
 1. is there an good way to send/inject a configurable timeout setting into the github (or any other) rule? Or a better place to watch for timeouts?
 2. after timeout, should there still be a github error in lint messages? Not if timeout==0?

2024-01-01 07:29 UTC, sindresorhus commented
1. I was not thinking of a configurable timeout, just make a hard-coded timeout with a sensible value.
2. Only if a URL was specified.

2024-01-01 07:30 UTC, sindresorhus requested changes

2024-01-01 07:30 UTC, sindresorhus commented on index.js
> +			throw new Error('Attempting to lint url while offline!');
```suggestion
			throw new Error('Cannot lint URL while offline.');
```

2024-01-01 18:40 UTC, WillForan commented
I think the default behavior is to time out already! I just didn't like waiting :)

It seems reasonable to reject this pull request -- awesome-lint does the reasonable thing already without command arguments sloshing around 2 files b/c one person is impatient.

If it's useful, I'm happy to make a separate very small pull for the `--depth 1` change -- and more so if you don't need me involved for the change. Kill the other parts of this request or DIY elsewhere. Whatever easier.

2024-01-01 19:03 UTC, sindresorhus commented
> If it's useful, I'm happy to make a separate very small pull for the --depth 1 change

👍

2024-01-01 19:03 UTC, closed without merging